### ISSUE TITLE
Alias "@id"/"@type" to "id"/"type"

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-rdf-to-json#29] opened 2016-02-25 13:42 UTC
Add this to the JSON-LD context:

``` javascript
"id": "@id",
"type": "@type"
```

Use "id" and "type in the data.

**Comment by dr0i** [comment] 2016-02-25 16:01
Adapting the context results in `Caused by: com.github.jsonldjava.core.JsonLdError: invalid type value: @type value must be a string or array of strings`. 
That's because the json-ld produces an array of objects:

```
"type" : [ {
    "@id" : "http://purl.org/dc/terms/BibliographicResource"
  }, {
    "@id" : "http://purl.org/ontology/bibo/Book"
  } ]
```

when dealing with these ntriples (where URIs in object position are, naturally, resources (json-speak: objects)): 

```
<http://lobid.org/resource/HT018454638> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/dc/terms/BibliographicResource> .
<http://lobid.org/resource/HT018454638> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/ontology/bibo/Book> .
```

What would work is of course to not produce resources in object position in the first place, like:

```
<http://lobid.org/resource/HT018454638> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "http://purl.org/dc/terms/BibliographicResource" .
<http://lobid.org/resource/HT018454638> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "http://purl.org/ontology/bibo/Book" .
```

=> 

```
"type" : [ "http://purl.org/ontology/bibo/Book", "http://purl.org/dc/terms/BibliographicResource" ]
```

but this is of course wrong. So, the lobid-rdf-to-json library must deal with this.

**Comment by dr0i** [comment] 2016-02-26 10:03
Deployed small test set , see http://lobid.org/resources-staging/HT015891797.

**Comment by dr0i** [comment] 2016-02-26 10:10
Copied also the context to the webserver : http://lobid.org/download/contextTmp.json.

**Comment by acka47** [comment] 2016-02-26 10:38
In http://lobid.org/resources-staging/HT015891797 "type" looks good but it still says `"@id": "http://lobid.org/resources/HT015891797"`, _with_ the ''@'.

**Comment by jschnasse** [comment] 2016-02-26 12:49
Hi @dr0i , your modification makes the current gaia index invalid. Therefore @fsteeg and me have copied your modified context to http://lobid.org/download/contextTmp-staging.json and removed the line `"type":"@type"` from http://lobid.org/download/contextTmp.json.

**Comment by dr0i** [comment] 2016-02-26 12:50
Ah, I thought that the id of the resource should keep it's `@`. Don't ask me why.

**Comment by dr0i** [comment] 2016-02-26 12:51
@jschnasse Douh - I hadn't thought about that. Thx!

**Comment by dr0i** [comment] 2016-02-26 15:11
Deployed small test set , see http://lobid.org/resources-staging/HT015891797.

**Comment by acka47** [comment] 2016-02-26 15:16
+1 (I can't find `"type": "@type" in the current context on http://lobid.org/download/contextTmp.json. I guess it will be added with this issue...

**Comment by dr0i** [comment] 2016-02-26 15:29
Yes I am working on that so that the small test set uses the staging context.

**Comment by dr0i** [comment] 2016-02-26 15:55
Deployed again, now with staging-context, see http://lobid.org/resources-staging/HT015891797.

**Comment by acka47** [comment] 2016-02-27 09:08
Now I see `@id` (with the "@") all over the example http://lobid.org/resources-staging/HT015891797.

**Comment by dr0i** [comment] 2016-02-29 08:19
That was probably a sideeffect of building the full index (saturday at 10am you hit that). Please have a look again.

**Comment by acka47** [comment] 2016-03-01 08:01
+1

**Comment by dr0i** [comment] 2016-03-01 08:08
Deployed to production, see e.g. http://lobid.org/resources/HT015891797.

**Comment by dr0i** [comment] 2016-03-01 08:18
Reopened because the nwbib does not work with the new index, e.g. http://test.nwbib.de/HT018486420 wouldn't show a details view. Assigning @fsteeg . (The new index ist the one with -staging as alias suffix at gaia).

**Comment by dr0i** [comment] 2016-03-01 08:23
Hm, I tested again against the new index and now it's working (no mor isbn/issn search page is viewed). (EDIT: that's because of @fsteeg, see hbz/nwbib#271)

**Comment by dr0i** [comment] 2016-03-11 16:07
> I can't find `"type": "@type" in the current context on http://lobid.org/download/contextTmp.json

And it is missing still ... will deploy the new one at monday , may have effects on @jschnasse .

**Comment by dr0i** [comment] 2016-03-14 09:55
Deployed to staging after checking with @jschnasse . Closing.

**Closed as completed by dr0i** 2016-03-14 09:55 UTC
Labels: nwbib-launch, API 2.0
